# File to setup the instance of VSCode in GitPod
# See https://www.gitpod.io/docs/references/gitpod-yml
image: mcr.microsoft.com/vscode/devcontainers/python:3.9
tasks:
  - init: bash setup_devcontainer.sh

vscode:
  extensions:
    - ms-python.python
    - wayou.vscode-todo-highlight
    - ms-azuretools.vscode-docker
    - silofy.hackthebox
