title = "gitleaks custom config"

[[rules]]
	description = "Detect private keys"
	regex = '''-----BEGIN (:?[A-Z\-\s]*)PRIVATE KEY-----'''
	tags = ["private-keys"]
	
[[rules]]
	description = "Detect passwords/secrets"
	regex = '''(?i:password|pass|pwd|passwd|secret)\s*(=|:)\s*[\w\d]+'''
	tags = ["passwords", "secrets"]
	
[[rules]]
	description = "Detect keys"
	regex = '''(?i:key)\s*(=|:)\s*[\w\d]+'''
	tags = ["keys"]

[[rules]]
	description = "Detect UUID/GUID"
	regex = '''[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'''
	tags = ["uuid", "guid"]
