name: Audit the toolbox image
env:
  IMAGE_NAME: "righettod/toolbox-pentest-web"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
      - name: Install docker-slim
        run: |
          curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
          docker-slim version
      - name: Build the toolbox image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }} --file Dockerfile
      - name: Apply docker-slim against the built toolbox image
        run: |
          docker-slim build ${{ env.IMAGE_NAME }}
      - name: List images
        run: |
         docker images
