name: Build DLL Hijacking library
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cygwin and setup compilers
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++ mingw64-i686-gcc-g++ mingw64-x86_64-gcc-g++
      - name: Compile the library for 32 and 64 bits Windows OS
        shell: powershell
        run: .\Build-Library.ps1
      - name: Upload library binaries
        uses: actions/upload-artifact@v2
        with:
          name: DLL_Hijacking_Compiled_Library
          path: library_dist/
