name: Build and deploy the toolbox image
env:
  IMAGE_NAME: "righettod/toolbox-pentest-web"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Build and Publish image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: "--compress --force-rm"
