name: Build and deploy the toolbox image
env:
  IMAGE_NAME: "righettod/toolbox-pentest-web"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Build and Publish image to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildoptions: "--compress --force-rm"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: ${{ env.IMAGE_NAME }}
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: 0
          severity: "LOW,MEDIUM,HIGH,CRITICAL"
          security-checks: "vuln,secret,config"
          ignore-unfixed: true
          hide-progress: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
