name: Build PostgreSQL extension
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find available PG versions and compile the extension against them
        run: |
          ls -l
          chmod +x build_pg_extension.sh
          bash build_pg_extension.sh
      - name: Upload extension binary
        uses: actions/upload-artifact@v1
        with: 
          name: Extension
          path: "*.so"
