name: Build the image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the image
      run: docker build . --file Dockerfile --tag toolbox:$(date +%s)
