name: Build the image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the image
      - uses: actions/checkout@v1    
      - run: docker build . --file Dockerfile --tag toolbox:latest
      - name: Publish image to DockerHub
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: righettod/toolbox-pentest-web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
